### ISSUE TITLE
Create a live demo version

### ISSUE THREAD

**Issue by DanAtkinson** [aspnet/MusicStore#149]
It'd be really nice if you would be able to publish the music store website on the web, presumably on Azure.

**Comment by ByteBlast** [comment]
I would appreciate this also.

**Comment by Praburaj** [comment]
This being a sample it is for users to have it hands on. I can't think it is useful to have a live running version.

**Comment by DanAtkinson** [comment]
I'm confused as to why you think it's not useful to have an official live demo site for projects such as these. In my opinion, that seems to be a somewhat short sighted decision.
