### ISSUE TITLE
Test are flaky when run locally via ./build

### ISSUE THREAD

**Issue by HaoK** [aspnet/MusicStore#253]
MusicStores tests consistently fail for me when run locally via ./build even when passing on CI.  Some combination of clean/upgrade/rerun eventually gets them to pass.  

Ideally ./build.cmd should run cleanly always

**Comment by Praburaj** [comment]
This should be fixed now. https://github.com/aspnet/MusicStore/commit/b0c989ce90f5f86f7118e895c527a2c7bde5ca87
