### ISSUE TITLE
MusicStore.Spa.Startup throws 'System.ArgumentException' occurred in Microsoft.AspNet.FileSystems.dll

### ISSUE THREAD

**Issue by Venomed** [aspnet/MusicStore#256]
Just cloned this repository and first thing I see on Spa project [Startup.cs](https://github.com/aspnet/MusicStore/blob/master/src/MusicStore.Spa/Startup.cs#L68) run is:

*An exception of type 'System.ArgumentException' occurred in Microsoft.AspNet.FileSystems.dll but was not handled in user code*
Additional information: *The path must be absolute.*

**Comment by Eilon** [comment]
The SPA project has been removed from this repo (in the dev branch). See https://github.com/aspnet/MusicStore/issues/537 for more info.
