### ISSUE TITLE
Bad layout for medium width page

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/MusicStore#266]
The page header overlaps the content when you have a medium width page:

![untitled](https://cloud.githubusercontent.com/assets/5921642/4741265/b545e386-5a14-11e4-8da5-5ba6851b9812.png)

**Comment by Praburaj** [comment]
@victorhurdugaci PRs welcome :smile:

**Comment by Eilon** [comment]
No plans to change this in the Music Store test app.
