### ISSUE TITLE
Detect when app is in debug environment and disable XHR timeouts

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/MusicStore#278]
Currently when you start debugging the server the client code quickly hits XHR timeouts. The app should detect when your debugging or in debug more (whatever) and configure a much longer (infinite?) XHR timeout in Angular's $http service provider.

**Comment by Eilon** [comment]
The SPA project has been removed from this repo (in the dev branch). See https://github.com/aspnet/MusicStore/issues/537 for more info.
