### ISSUE TITLE
Investigate using TypeScript Definition Manger (TSD) instead of dt-* bower packages

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/MusicStore#287]
https://www.npmjs.org/package/tsd
https://github.com/DefinitelyTyped/grunt-tsd

Apparently this is the new hotness for managing TypeScript definitions directly from the Definitely Typed repo without using a package manager (e.g. NuGet or Bower).

**Comment by lucamorelli** [comment]
any news about this?

**Comment by Eilon** [comment]
The SPA project has been removed from this repo (in the dev branch). See https://github.com/aspnet/MusicStore/issues/537 for more info.
