### ISSUE TITLE
ViewState

### ISSUE THREAD

**Issue by branciat** [aspnet/MusicStore#325]
Hi,

The file _ViewStart.cshtml must to be rename to lowercase for the OS Linux. See the discussion below

http://forums.asp.net/t/2022947.aspx?_Layout+cshtml+not+loaded+on+linux

**Comment by Tragetaschen** [comment]
No :)

Beta1 is not consistent. The current HEAD uses [_ViewStart.cshtml](https://github.com/aspnet/Mvc/commit/5b1eae494ea25bb88c34ed285dd76e6bcb2db99e#diff-3b8b6fe6d5352a75ce9e1fa8b0a2185dR16) as the casing.

**Comment by branciat** [comment]
Ok thanks :)
