### ISSUE TITLE
integration of server side code analisys

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/MusicStore#337]
Hi,
  now that we have ts linting in the pipeline, is there any plan to add to the pipeline server side validation too (former fxcop, actually seems to me vs code analisys ) and stylecop?
  another question: if I want to customize the pipeline and I want to write my own module, is it possible to write the core using .net and wrap in a node.js module?

**Comment by Eilon** [comment]
No plans to change this in the Music Store test app.
