### ISSUE TITLE
Make tests run in parallel

### ISSUE THREAD

**Issue by Praburaj** [aspnet/MusicStore#343]
Currently it uses fixed port numbers. Need to make it use free ports and run all tests in parallel to save time.

**Comment by rynowak** [comment]
This is related to what we had discussed earlier about centralizing this infrastructure between MVC and Music Store. Let's discuss after beta3 locks.

**Comment by Praburaj** [comment]
This is complete. https://github.com/aspnet/MusicStore/commit/29ef86fad312c29c1c63192236f55ec619319132

@Tratcher @rynowak
