### ISSUE TITLE
Help with WebPages and bower.json

### ISSUE THREAD

**Issue by kscott5** [aspnet/MusicStore#353]
I don't have visual studio I'm running from command-line with notepad++ ad my editor from public computer at local library. But need help with the following two issues.

How do you enable webpages. In the previous version of ASP.Net this was accomplished using the web.config and appsettings section.

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <appSettings>
	<add key="webpages:Enabled" value="true"/>
  </appSettings>
</configuration>
```

Secondly, how do you enable the use of the bower.json file? I ask because when executing

```powershell
kpm restore -s $env:KRE_FEED -s https://www.nuget.org/api/v2 --no-cache
```

it never pulls client-side libraryies. Lastly, how does the bower.json file related to wwwroot and StaticFiles.

Update:

Ok, bower package manager that require nodejs, npm and git. All which I have. So, the really question is will the next version of Visual Studio 2015 install this open source tools or have a set of tools that function similar?

**Comment by davidfowl** [comment]
1. There is no webpages yet
2. You use bower, kpm is not bower. http://bower.io
3. https://github.com/aspnet/Home/issues/194#issuecomment-63239874
