### ISSUE TITLE
Do controllers still sit in front of everything except the routing subsystem? 

### ISSUE THREAD

**Issue by heathyates** [aspnet/MusicStore#399]
The Professional ASP.NET MVC5 book by Galloway et al. in chapter 2 describes controllers as sitting in front of everything except the routing subsystem in MVC5 (page 32). Is this still true in ASP.NET5? I doubt it now given how startup.cs is suggestive of major changes behind the scene I can't quite see as a developer.

**Comment by rynowak** [comment]
Can you define what you mean by *everything*? They certainly sit in front of your views.

A few things that run 'in front of' controllers in a typical MVC app:
- Middleware
- Routing
- ActionConstraints (formerly know as ActionSelectorAttribute)
- Filters

Startup.cs code runs once at startup to configure your app. It shouldn't have any direct role in handling requests.

**Comment by heathyates** [comment]
I quote page 32 of the book I read, "ASP.NET MVC implements the front controller variant of the MVC pattern, and the controller sits in front of everything except the routing system, as discussed in Chapter 9".

**Comment by Eilon** [comment]
@heathyates though there are significant changes between MVC 5 and MVC 6, the overall pattern is largely the same:

1. There's a hosting layer that runs first, and includes a concept of running various "modules".
2. One of these "modules" is routing
3. If routing matches the URL for MVC, then MVC runs its code (the controllers, action filters, views, etc.)

In ASP.NET 4.x and earlier, the "modules" were ASP.NET IHttpModules. In ASP.NET 5 these are replaced by ASP.NET middleware.

But the overall pattern and concepts are the same.

**Comment by heathyates** [comment]
@Eilon 

Thank you for your prompt reply @Eilon and @rynowak . I am impressed and humbled by having such high level developers talk to a relative n00b as myself. I will close this issue shortly, but please, allow me one additional question. 

What source code would best help me understand the significant changes that have come to ASP.NET5? For example, in startup we register the applicationDBcontext. We can then write a constructor in a controller that can grab applicationDBcontext as a parameter. I think this is DI, but I honestly don't understand how this and other aspects of ASP.NET work and it is those kind of "under the hood" details that I hunger for. 

Maybe what I am asking @Eilon and @rynowak seems stupid, but I would rather ask something stupid in the hopes that I don't stay ignorant. In that, I humbly thank you for your assistance and helping me learn. I'll do all I can to pay it forward in the future.

**Comment by Eilon** [comment]
I think for right now, the best way to see the differences is to compare the original [MVC 5 music store](https://github.com/aspnet/MusicStore/tree/master/src/MvcMusicStore) and the updated [MVC 6 music store](https://github.com/aspnet/MusicStore/tree/master/src/MusicStore).

We're working on having proper guidance as well as migration guides as part of our documentation project but there's nothing published just yet as far as I know.

**Comment by Eilon** [comment]
Oh we did publish an MSDN article at https://msdn.microsoft.com/en-us/magazine/dn879354.aspx that has some brief mentions about migrating, but expect to see more in the future.

**Comment by heathyates** [comment]
@Eilon Thank you for the excellent answer. Your response is extremely useful and helped me quantify what I want to learn about. How can I become a professional with the new HTTP pipeline that is coming out and learn how ASP.NET processes it? I just don't want to a tool user, but try to be a tool maker too. It seems to me that the new HTTP pipeline and middleware is at the heart of the new application paradigm. 

Again, I cannot thank you for your last post/link enough. :)

**Comment by Eilon** [comment]
I think the best thing to do is to just use the system to build a real app - that way you get to learn lots of different parts of the system in real scenarios.

**Comment by heathyates** [comment]
@Eilon Fair enough, and something I am doing right now. However, your advice makes me feel better about that approach. I will wait patiently for when more information about the nuts and bolts becomes available. I also bought a book on CLR recently. I don't want to just use the magic, but understand it. ;-) Thanks @Eilon

**Comment by rynowak** [comment]
:+1: to everything @Eilon said.

Also in the context of the quote:

> "ASP.NET MVC implements the front controller variant of the MVC pattern, and the controller sits in front of everything except the routing system, as discussed in Chapter 9".

It's still true that the `Controller` in MVC acts as a front-controller in design pattern terms. All of your business logic will still sit behind your controllers.


All the things that I mentioned (filters, middleware) typically address cross-cutting-concerns like auth, logging, etc.

**Comment by heathyates** [comment]
@rynowak Your comments are extremely illuminating. I took the quote out of it's intended context and was thinking about it architecturally. Logically, from a developer point of view, I see indeed how the business logic will still sit behind our controllers. 

There is so much to learn and I appreciate your gentle answers and patience. :)
