### ISSUE TITLE
There's no compatibility with beta3

### ISSUE THREAD

**Issue by EduardoPires** [aspnet/MusicStore#400]
There's no compatibility with beta3

**Comment by Eilon** [comment]
What exactly is the problem? Which branch were you using?

**Comment by EduardoPires** [comment]
I'm using beta3.

**Comment by Eilon** [comment]
Ah indeed it hasn't been updated to point to beta3. I'll follow up.

**Comment by Praburaj** [comment]
@EduardoPires - master branch now contains beta3 code. Could you try again. And could you try unloading E2ETests project from the solution before trying to build.

**Comment by Praburaj** [comment]
@EduardoPires 
And there is another tooling issue described below (From: https://github.com/aspnet/MusicStore/issues/374)

>Tooling disables the nuget.org feed while loading the solution resulting in package restore failures. Work around is to go and manually enable the feed after launching the solution. To restore the packages go ahead and hit save on the project.json files. Note: See (3) below before hitting save. 

Work around is:
>(1) is a known issue http://nuget.codeplex.com/workitem/4397. A good work around will be to create a Nuget package source named NugetTotal with the same feed url as Nuget.org in the nuget package sources dialog. This will make sure that the feed is not automatically disabled.

**Comment by EduardoPires** [comment]
@Praburaj Ok I'll try this new version. Thank you!
