### ISSUE TITLE
MusicStore should precompile it's views

### ISSUE THREAD

**Issue by shhsu** [aspnet/MusicStore#409]
MusicStore should precompile its views as we already do this in template MVC projects. This would improve startup performance for those why try out MusicStores

**Comment by shhsu** [comment]
@Praburaj @troydai @yishaigalatzer @jhawk42 @davidfowl

**Comment by Tragetaschen** [comment]
Note that precompilation will not work with any available release of Mono. See aspnet/XRE#1048. The fix is available in the 4.0 branch.

**Comment by Praburaj** [comment]
This is complete now.
