### ISSUE TITLE
Reenable OpenId + NTLM tests

### ISSUE THREAD

**Issue by HaoK** [aspnet/MusicStore#412]
Security changes appear to have broken these tests, skipping tests on CI so build is unblocked, will investigate these failures and reenable

**Comment by Praburaj** [comment]
The open id connect middleware is unable to deserialize the state into AuthenticationProperties object. Resulting in the following warning: 

[WARNING:Microsoft.AspNet.Authentication.OpenIdConnect.OpenIdConnectAuthenticationMiddleware] The state field is missing or invalid.

https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication.OpenIdConnect/OpenidConnectAuthenticationHandler.cs#L265

This is probably causing the authentication to fail.

**Comment by HaoK** [comment]
Should be fixed now
