### ISSUE TITLE
AddEntityFrameworkStores<MyContext>() is not working when using IdentityUser<int>

### ISSUE THREAD

**Issue by Ciantic** [aspnet/MusicStore#421]
The `AddEntityFrameworkStores<MyContext>()` throws runtime error if one has these:

    public class User : IdentityUser<int>
    {
    }
    
    public class UserRole : IdentityRole<int>
    {
    }
    
    public class MyContext : IdentityDbContext<User, UserRole, int>
    {
    }

It all works if I remove `int` from `IdentityRole` and `IdentityUser` and change last `int` to `string`. However I would like to have integer Ids.

**Comment by Eilon** [comment]
@HaoK @divega can you guys take a look?

**Comment by HaoK** [comment]
Try AddEntityframeworkStores(MyContext,int)

**Comment by Ciantic** [comment]
@HaoK ah I somehow missed that. This does work yes, thank you.  `AddEntityFrameworkStores<MyContext, int>()`

Though I got another problem, the RoleManager cannot create auto incrementing ID when using integers as Id's. I'm using InMemoryStore for testing purposes, the auto incrementing id's do work for my own models when using the simple `DbSet.Create` without specifying the Id.
