### ISSUE TITLE
Consider using FromServices attribute on an action's parameter instead of property injection.

### ISSUE THREAD

**Issue by kichalla** [aspnet/MusicStore#453]
Since MVC provides a way to model binding services from DI, we should look into changing the current controllers to have the `FromServices` attribute decorated on an action's parameter rather than the property injection that we currently have. 

The property injection change was recently made for making unit testing easy, but this does not clearly indicate what an action is dependent on.

Example:
For the following case:
https://github.com/aspnet/MusicStore/blob/dev/src/MusicStore/Controllers/StoreController.cs#L46

``` c#
public async Task<IActionResult> Details(int id, [FromServices] IMemoryCache cache)
```

**Comment by Praburaj** [comment]
@kichalla could you send a PR with the changes?

**Comment by Eilon** [comment]
No plans to change this in the Music Store test app.
