### ISSUE TITLE
(Support / Documentation) Difficulty opening with VS 2015

### ISSUE THREAD

**Issue by joelcollinsdc** [aspnet/MusicStore#476]
I tried to get started learning about this project today and was unable to get very far.  Perhaps I didn't find the right documentation?

1) download and open visual studio (professional) 2015 RC ( I was on an azure server 2012 instance if that matters)
2) clone this repo
3) When opening the solution in visual studio, receive messages stating that the version of the sql express database is not supported and asking if upgrading is desired.  I clicked yes.
4) Set MVCMusicStore as the startup project and click Build / Debug.  Received an error, found out that a "manual build" is needed first, and did that, and got past that error.
5) Now upon building and running, it said that the database connection was unavailable and possibly this is due to my connection strings.  Somehow my connection strings all pointed to localdb/v11.0, which maybe got written in there from step 3.  I changed these all to MsSQLLocalDB based on google searches.
6) Not sure if this was some kind of mental block, but even though the startup project was MVCMusicStore, MusicStore.SPA kept loading first when I clicked Build.  I had to navigate to the view folder and then say "view in browser" for the right project to actually run.
7) No static files were being shown (all 404)

**Comment by joelcollinsdc** [comment]
The only documentation for running this in visual studio said:

If you have Visual Studio 2015
Open MusicStore.sln in Visual Studio 2015 and run the individual applications on IIS Express.

Perhaps I missed some?

**Comment by punkouter** [comment]
6. Same thing here.. Confusing

I cannot get a valid localdb connection even though I verified the connection in SQL Management Studio.. No idea what is wrong there

**Comment by godna** [comment]
about  6)  : 
Open the property of project , click Web, then make sure the "project URL" of the two project("MVCMusicStore","MvcMusicStore.Spa") is diffrent.

maybe the URL conflict Cause this problem.


about  connection:
1:find your SqlLocalDB Path
such as "C:\Program Files\Microsoft SQL Server\120\Tools\Binn\"
2:Go to the path in cmd.exe
3:"C:\Program Files\Microsoft SQL Server\120\Tools\Binn\SqlLocalDB info"  you'll see the instance you have.
4.change you  connectionString with the instance you have.  such as "Data Source=(LocalDb)\Projects"

maybe  don't have the instance "v11.0" caush the problem.

**Comment by punkouter** [comment]
I got the right name for localDb... And it creates the data.. but then something else is going wrong.. see

https://github.com/aspnet/MusicStore/issues/482

**Comment by Eilon** [comment]
Haven't seen any issue with this in quite a while.
