### ISSUE TITLE
ArgumentNullException: Value cannot be null.  Parameter name: hashedPassword

### ISSUE THREAD

**Issue by Bartmax** [aspnet/MusicStore#477]
If I log in using twitter and then try to log in using the email with any password returns an error

```
An unhandled exception occurred while processing the request.

ArgumentNullException: Value cannot be null.
Parameter name: hashedPassword
Microsoft.AspNet.Identity.PasswordHasher`1.VerifyHashedPassword(TUser user, String hashedPassword, String providedPassword)

```

because the user exist but doesn't have a password.

**Comment by HaoK** [comment]
This is an identity issue, I'll take a look

**Comment by HaoK** [comment]
@suhasj I thought you were looking at something like this?  Did you already check the fix for this in?

**Comment by suhasj** [comment]
Not fully sure. I don't think I have seen anything like this
