### ISSUE TITLE
[question] ASPNET_ENV Information inside the StartupNtlmAuthentication.cs

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/MusicStore#481]
Is this information still relevant?

https://github.com/aspnet/MusicStore/blob/f0998dffbc5e6846515787eb931bd979753efd58/src/MusicStore/StartupNtlmAuthentication.cs#L20-L30

**Comment by mkArtakMSFT** [comment]
Closing this issue as there was no community involvement for quite a while now.
