### ISSUE TITLE
Database is created but then there is an error (ASPNET5 project)

### ISSUE THREAD

**Issue by punkouter2018** [aspnet/MusicStore#482]
Any idea what is happening here? Here is the output.

A database operation failed while processing the request.

AggregateException: One or more errors occurred. 
AggregateException: One or more errors occurred. 
AggregateException: One or more errors occurred. 
AggregateException: One or more errors occurred. 
AggregateException: One or more errors occurred. 
AggregateException: One or more errors occurred. 
AggregateException: One or more errors occurred. 
AggregateException: One or more errors occurred. 
SqlException: Invalid object name 'Album'. 

There are pending model changes for MusicStoreContext

Scaffold a new migration for these changes and apply them to the database from the command line:

> dnx . ef migration add [migration name] 
> dnx . ef migration apply

**Comment by mkArtakMSFT** [comment]
Closing this issue as there was no community involvement for quite a while now.
