### ISSUE TITLE
Remove or fix Helios.cmd

### ISSUE THREAD

**Issue by rubenprins** [aspnet/MusicStore#510]
Currently, the Helios.cmd script in src/MusicStore will spawn an IIS Express instance that will give the error

> Unable to resolve project 'wwwroot' from [path]\src\MusicStore\wwwroot

Either `src/MusicStore/wwwroot/web.config` should be updated to include the proper `runtime-path`/`dnx-app-base` settings (i.e., `..`), or Helios.cmd should be removed to avoid confusion.

(Note that README.md should be updated as well, should you choose to remove Helios.cmd.)

**Comment by davidfowl** [comment]
master branch?

**Comment by rubenprins** [comment]
Yep: master, dev, release, they all still have Helios.cmd and references to it from README.md ("If you don't have Visual Studio 2015").

Should I be looking at another branch?

**Comment by leandermurphy** [comment]
I also just hit this issue.  Is there a web.config change that can be done as a work around?

**Comment by saltysnacks** [comment]
I also encountered this issue.  I was able to workaround by adding the following to my web.config...

```xml
<appSettings>
  ...
  <add key="dnx-app-base" value=".." />
</appSettings>
```

".." as src/musicstore/wwwroot is the location of the web.config and the app root dir is at src/musicstore.

**Comment by leandermurphy** [comment]
That works for me.  Thanks!
