### ISSUE TITLE
Update and reenable open id tests

### ISSUE THREAD

**Issue by HaoK** [aspnet/MusicStore#511]
@kichalla I investigated the failure, looks like the test and verification just needs to be updated.

Due to how SignOut redirects immediately happen now, the change to music store is now: to return empty result.  Inside AccountController.LogOff:

```
return RedirectToAction("Index", "Home"); => new EmptyResult()
```

I'm not exactly sure what the test needs to verify, but I debugged it and the old assertions are no longer valid.

**Comment by kichalla** [comment]
@HaoK I tried running the MusicStore sample with the above mentioned change, but the page does not get redirected on LogOff and is a blank page. Is there any other place where we need to provide the redirection url?

**Comment by HaoK** [comment]
Ah yes sorry, so you can set redirect via AuthenticationProperties.RedirectUri as part of the SignOut call.

The other case when its not OpenId can continue to return the old value.  That should work better

**Comment by mkArtakMSFT** [comment]
Closing this issue as there was no community involvement for quite a while now.
