### ISSUE TITLE
Cannot restore MusicStore application

### ISSUE THREAD

**Issue by tinganho** [aspnet/MusicStore#514]
I'm getting this error when I run `dnu restore` in `src/MusicStore/` on my mac:
```
...
Warning: FindPackagesById: System.Runtime.Serialization.Primitives
  Too many open files
  GET https://nuget.org/api/v2/FindPackagesById()?id='System.Runtime.Serialization.Primitives'
Error: FindPackagesById: System.Runtime.Serialization.Primitives
  Too many open files
...
```

**Comment by tinganho** [comment]
```
$ dnu --version
Microsoft .NET Development Utility
 Version:      1.0.0-beta7-12264
 Type:         Mono
 Architecture: x64
 OS Name:      Darwin
```

**Comment by peterblazejewicz** [comment]
The same here.

However: if I prepare version of application just copying content, removing references to  parent files, etc, I can restore and run application (also OS X/Mono 4.* as above):
https://github.com/peterblazejewicz/asp5-mvc6-examples/tree/master/MusicStore

**Comment by Eilon** [comment]
We haven't seen this error in quite some time now and we've fixed a lot of issues in `dnu`, so closing this.
