### ISSUE TITLE
Are you really bringing in SignalR and CodeGenerators.Mvc in project.json for beta6? 

### ISSUE THREAD

**Issue by heathyates** [aspnet/MusicStore#516]
![error](https://cloud.githubusercontent.com/assets/1896424/8967360/e7b11d40-35fb-11e5-83b5-e5952d3a89b3.PNG)

I'm confused. First, according to what I know, there is no beta 6 for CodeGenerators.Mvc. See [here](https://www.nuget.org/packages/Microsoft.Framework.CodeGenerators.Mvc/). Second, I get the error above when I try to invoke `dnu restore`. 

However, I noticed that you have these dependencies specified in your project.json. Is this breaking for you as well, or is there a nuget source you are using that I don't have? 

I am using VS15 RTM. Before I took a look at your updated mvc store, there is this discussion going on [here](https://github.com/aspnet/SignalR-Server/issues/109) as well. So clearly, we are either in a situation where MusicStore [project.json](https://github.com/aspnet/MusicStore/blob/master/src/MusicStore/project.json) is wrong or there is something I am doing wrong (please let it be me).

**Comment by Eilon** [comment]
The `NuGet.config` file for MusicStore specifies the `MyGet.org/aspnetmaster` feed, which has these packages.

Did you clone the entire repo, or maybe some files are missing?

**Comment by heathyates** [comment]
@Eilon I had problems with Nuget. After I resolved them, I saw the issue go away. Thanks a lot.
