### ISSUE TITLE
Inline JavaScript code with C# Razor comments

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/MusicStore#519]
The main example ships with syntax error due to using Razor comment syntax in inline JS script tag in main template:
https://github.com/aspnet/MusicStore/blob/master/src/MusicStore/Views/Shared/_Layout.cshtml#L28
```razor
<script>
        @*To display what\'s new in the store*@
        $(function () {
            $.connection.hub.logging = true;
            var announcementsHub = $.connection.Announcement;
```
It could work in VS, but breaks my Atom editor. 
Thanks!

**Comment by dougbu** [comment]
Note the change suggested in the PR does not do the same thing. A Razor comment doesn't add bits to the generated response; a JavaScript comment (or an HTML comment) does.

Separately, how well does the Atom editor handle Razor expressions like `@ViewBag.Title` or `@await Component.InvokeAsync("CartSummary")`? In other words does fixing this issue just move the needle from unusable to not worth using?

**Comment by peterblazejewicz** [comment]
OK, let me explain:
* we are not tied to Visual Studio anymore, correct assumption? 
* I agree - Razor is stripped out - so maybe we could just move comment out of `<script>` tag? Both VS users and others will be happy:
```razor
@*To display what\'s new in the store*@
<script>
```
* the Razor comment is JavaScript is not a thing maybe known to seasoned VS/MVC developers
* the VS Code has also problem with such code:
![20150804225859](https://cloud.githubusercontent.com/assets/14539/9072608/7ae1fd5a-3afc-11e5-9df8-941f5004cde9.jpg)

Atom handles things quite well thanks to OmniSharp otherwise.
Thanks!

**Comment by dougbu** [comment]
Agree VS is no longer the sole focus. My question was about the Atom experience after fixing this e.g. what else might need to change?

Thanks for bringing up VS Code; [their docs](https://code.visualstudio.com/Docs/languages) show HTML is not a supported language (yet?). Not a big surprise Razor sources confuse it.

**Comment by Eilon** [comment]
@kichalla can you merge once the CI is... stable?
