### ISSUE TITLE
Stop using comments in JSON files even if supported by some IDEs

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/MusicStore#524]
The problem is surfacing from time to time, e.g.:
https://github.com/aspnet/MusicStore/pull/248
The JSON does not allow comments but as VS does not break, the comments are using. For example in `config.json` file:
https://github.com/aspnet/MusicStore/blob/master/src/MusicStore/config.json#L9-L11
We have that problem fixed on other related project:
https://github.com/OmniSharp/generator-aspnet/issues/82
and we simply always strip away comments from JSON as we are shipping universal code for everyone.
The comments does not break in VS and VS Code, but simply do not [usually] work in other places - e.g. here on GitHub source view.
The project could contain README.md to contain configuration related information if required.

**Comment by Eilon** [comment]
No plans to change this in the Music Store test app.
