### ISSUE TITLE
MusicStore 1.0.0-beta6 depends on "Microsoft.AspNet.SignalR.Server": "3.0.0-beta6" but that package is not available

### ISSUE THREAD

**Issue by jeremymeng** [aspnet/MusicStore#529]
The latest version of Microsoft.AspNet.SignalR.Server on nuget.org is 3.0.0-beta5.

**Comment by BrennanConroy** [comment]
@muratg

**Comment by muratg** [comment]
@kichalla Could you remove the SignalR dependency? It looks like it's not used anyways.

**Comment by kichalla** [comment]
commit 09721166972995634f7af91a645f22d71f814f54
