### ISSUE TITLE
Deployed to Azure successful...hit details page gives error

### ISSUE THREAD

**Issue by brianlangbecker** [aspnet/MusicStore#530]
Hi,

So I am bit rusty on development but I managed to get a fresh environment setup with 2015 express web, muddle may way through all the package stuff.   While the IISexpress version never seems to render successful I pushed the project  toAzure Websites with Azure SQL.  And it works great.

The only issue I run into is every time I go to the details page it tosses an error.  I have tried to play with the query with no luck...and I am rusty enough that I need some pointers.

http://musicstore3_bdl.azurewebsites.net/Store/Details/5  results in..

Error

An error occurred while processing your request

I am using the MvcMusicStore project.  Any pointers for figuring this out would be helpful and I am very much grateful for the time anyone spends in responding.

**Comment by Eilon** [comment]
Sorry for the delay on responding to this, but there isn't enough information here to reproduce the error. If you still see an error, please post the error text, a screenshot, or other information that will help us diagnose the issue. Thanks!
