### ISSUE TITLE
Clear up MusicStore repo

### ISSUE THREAD

**Issue by Eilon** [aspnet/MusicStore#537]
* MusicStore - keep
* MusicStore.Spa - move to Entropy
* MvcMusicStore - delete
* MvcMusicStore.Spa - @DamianEdwards will give it a new home

**Comment by Eilon** [comment]
@kichalla let's chat about this one.

**Comment by HaoK** [comment]
Yay, no more manually removing MvcMusicStore from my sln :)

**Comment by kichalla** [comment]
2c1f1a277a014f3670892966c5d32662f5674894
