### ISSUE TITLE
MusicStore src references test

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/MusicStore#549]
That's totally wrong and blocks publish and Nano testing.

https://github.com/aspnet/dnx/issues/2986

cc @kichalla

**Comment by kichalla** [comment]
A temporary workaround would be is to rename the folder `test` to `tests` before we understand and fix the references itself?

**Comment by victorhurdugaci** [comment]
If you do that, you have to update the build script to look in the new folder. KoreBuild only looks in "test"

**Comment by Eilon** [comment]
@kichalla @victorhurdugaci is this bug still an issue? Seems to me that it isn't and we can close, right?
