### ISSUE TITLE
Sql Server could not be connected in Ubuntu environment 14.04

### ISSUE THREAD

**Issue by madhavan281981** [aspnet/MusicStore#564]
Hello Folks,
     I am learn asp.net5 and was going through the sample MVC MusicStore application (from dev branch) with Beta8 (1.0.0-beta8 dnvm) installed in both windows and linux platform. The Startup.cs checks for the running platform windows/linux. If the running platform is Linux, it store the information in InMemoryDatabase. When i try to change this option (similar to else section connect to a Sql Server)  and run against  Azure Sql DB it gives me SNI Handle error in Ubuntu 14.04 environment. 

Stack Trace Message
error   : [Microsoft.Data.Entity.Query.QueryContextFactory] An exception occurred in the database while iterating the results of a query.
info    : [MusicStore.Program] Exception
info    : [MusicStore.Program] Message: The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception.
info    : [MusicStore.Program] System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.SNILoadHandle' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'sni.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at System.Data.SqlClient.SNINativeMethodWrapper.SNIInitialize(IntPtr pmo)
   at System.Data.SqlClient.SNILoadHandle..ctor()
   at System.Data.SqlClient.SNILoadHandle..cctor()
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.TdsParser..cctor()
Application startup exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AggregateException: One or more errors occurred. ---> System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.TdsParser' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.SNILoadHandle' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'sni.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at System.Data.SqlClient.SNINativeMethodWrapper.SNIInitialize(IntPtr pmo)
   at System.Data.SqlClient.SNILoadHandle..ctor()
   at System.Data.SqlClient.SNILoadHandle..cctor()
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.TdsParser..cctor()
   --- End of inner exception stack trace ---
   at MusicStore.Models.AdvWorksData.GetCurrency(IServiceProvider serviceProvider)
   at MusicStore.Models.AdvWorksData.<InsertTestData>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

The same code functionality works perfectly as expected in windows environment. Does the Linux version of beta8 lacks some of the features to connect to Sql Server when compared windows version?

Any thoughts/inputs will be helpful.

Thanks
Madhavan

**Comment by danroth27** [comment]
SqlClient is not available on Linux in beta8. We are working on adding support for xplat SqlClient in RC1.

**Comment by madhavan281981** [comment]
Hello,
           Thanks for the response. After updating the DNVM to RC1 (1.0.0-Rc1-Final), the still still exists in ubuntu environment.

**Comment by nteague22** [comment]
The last comment still stands in a windows environment running dotnet5.5 library code, dnxcore50 has intermittent issues, but dotnet5.5 enabled DataReader code fails
