### ISSUE TITLE
Heroku build error

### ISSUE THREAD

**Issue by alexsandro-xpt** [aspnet/MusicStore#574]
After click in Deploy to Heroku button and them Deploy for free.

The build process fire a error:

There was an issue building your app. This can mean your app.json's project is not a valid Heroku application. Please ensure your app is deployable to Heroku and try again.

    -----> Fetching set buildpack https://github.com/heroku/dotnet-buildpack.git... done
    -----> ASP.NET 5 app detected
    installing https://github.com/friism/mono-builder/releases/download/v4.0.1.44/mono-4.0.1.44.tar.gz
    Downloading dnvm as script to '/app/.dnx/dnvm'
    Appending source string to /app/.profile
    Type 'source /app/.dnx/dnvm/dnvm.sh' to start using dnvm
    Architecture must be x86 or x64.
     !     Push rejected, failed to compile ASP.NET 5 app

What happened?

**Comment by greenygh0st** [comment]
Same issue

**Comment by Eilon** [comment]
Mono is no longer supported so we removed the Heroku deploy button in this PR: https://github.com/aspnet/MusicStore/pull/708
