### ISSUE TITLE
HttpClient redirect fails in Mono 4.0.5 causing E2E tests to fail

### ISSUE THREAD

**Issue by kichalla** [aspnet/MusicStore#578]
The following issue filed on Mono describes the problem
https://bugzilla.xamarin.com/show_bug.cgi?id=30604

Note that Travis CI runs on Mono 4.0.5 version

The repro for the issue is in *first* comment and the **comment 8** mentions about this being fixed in 4.2 which I was able to verify as my Ubuntu vm has 4.2.1

Currently the 'tests' run only on dnx451, which means only Mono...we should investigate to see if we can make the tests run on CoreClr to avoid hitting these issues...

@muratg

**Comment by muratg** [comment]
Yes, we should make the tests run on CoreCLR as soon as possible.

cc @Eilon

**Comment by kichalla** [comment]
This has been fixed in commit. We now use CoreClr to run tests. 5c2ef70cae9116f68d2df3e94293b31d7108f8e3
