### ISSUE TITLE
Problem in executing the source codes

### ISSUE THREAD

**Issue by dongliu828** [aspnet/MusicStore#583]
I have downloaded the zip file, unpacked it, compiled it, and executed it with Visual Studio 2015 Community on IIS Express.

Compilation is OK.   Executing the project throws an error in Program.cs file as -

An exception of type 'System.IO.FileLoadException' occurred in Microsoft.AspNet.Hosting.dll but was not handled in user code

Additional information: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)

**Comment by jarrettv** [comment]
Also seeing this issue

**Comment by xaclincoln** [comment]
same issue as @jarrettv  when running samples in Routing repository.

**Comment by Cuiqs76** [comment]
same issue as @jarrettv when open the project. the reference lib couldn't load.

**Comment by chancewen** [comment]
same issue as @jarrettv .

**Comment by Cuiqs76** [comment]
@jarrettv @xaclincoln @chancewen  Have you solved the problem?

**Comment by capesean** [comment]
@jarrettv that's probably caused by an assembly version mismatch. Check if your project is on the right (RC2?) version.

**Comment by Eilon** [comment]
This sounds like a mismatch of builds between the DNX and the packages. Both the public build CI and internal build CI have been green (until a few days ago, when we just renamed everything and caused some breaks).

**Comment by AirBar84** [comment]
Hardcore breakages... argh... very frustrating.

**Comment by Eilon** [comment]
@AirBar84 indeed, and we're sorry about that - we're working as hard as we can to get all the issues resolved.

**Comment by chancewen** [comment]
@Eilon thank you !

Do you mean that we need to wait a few days for the new version of DNX  to match the package ?

Currently through the dnvm, I can get the latest version is 1.0.0.rc2-16357 on windows, it does not work.

**Comment by Eilon** [comment]
@chancewen yes, there are a few different big changes going on right now and we have as many people on the team as possible working on finishing up the work.

As always, the most stable builds (RC1) are on nuget.org and continue to work.

**Comment by filipw** [comment]
same here, there is no way to run anything from the CI builds because `1.0.0.rc2-16357` crashes with this exception

**Comment by nockawa** [comment]
Almost no documentation, only one real sample that's not working: asp.net core is like being in the jungle right now it seems...
Is there a way to get it working ?

**Comment by Eilon** [comment]
@nockawa this is a really really really big change so it's taking us a bit longer than we were expecting. Some apps definitely already work, but MusicStore perhaps not.

**Comment by nockawa** [comment]
Can you point me to some "real world" samples that are working right now?
I would like to learn about authentication, with external provider, session state, cache.
Any working samples would do.
Thanks
