### ISSUE TITLE
Problems Compiling MusicStore.

### ISSUE THREAD

**Issue by briancabbott** [aspnet/MusicStore#584]
I'm currently unable to compile the Music Store sample Application. The errors that I'm current receiving are: 

```
MusicStore\src\MusicStore\StartupOpenIdConnect.cs(136,48): DNX,Version=v4.5.1 error CS1660: Cannot convert lambda expression to type 'OpenIdConnectOptions' because it is not a delegate type
MusicStore\src\MusicStore\Startup.cs(165,43): DNX,Version=v4.5.1 error CS1660: Cannot convert lambda expression to type 'FacebookOptions' because it is not a delegate type
MusicStore\src\MusicStore\Startup.cs(171,41): DNX,Version=v4.5.1 error CS1660: Cannot convert lambda expression to type 'GoogleOptions' because it is not a delegate type
MusicStore\src\MusicStore\Startup.cs(177,42): DNX,Version=v4.5.1 error CS1660: Cannot convert lambda expression to type 'TwitterOptions' because it is not a delegate type
MusicStore\src\MusicStore\Startup.cs(199,51): DNX,Version=v4.5.1 error CS1660: Cannot convert lambda expression to type 'MicrosoftAccountOptions' because it is not a delegate type
MusicStore\shared\Mocks\MicrosoftAccount\TestMicrosoftAccountEvents.cs(18,25): DNX,Version=v4.5.1 error CS1061: 'OAuthCreatingTicketContext' does not contain a definition for 'Principal' and no extension method 'Principal' accepting a first argument of type 'OAuthCreatingTicketContext' could be found (are you missing a using directive or an assembly reference?)
MusicStore\shared\Mocks\MicrosoftAccount\TestMicrosoftAccountEvents.cs(29,25): DNX,Version=v4.5.1 error CS1061: 'OAuthCreatingTicketContext' does not contain a definition for 'Principal' and no extension method 'Principal' accepting a first argument of type 'OAuthCreatingTicketContext' could be found (are you missing a using directive or an assembly reference?)
MusicStore\shared\Mocks\Google\TestGoogleEvents.cs(18,25): DNX,Version=v4.5.1 error CS1061: 'OAuthCreatingTicketContext' does not contain a definition for 'Principal' and no extension method 'Principal' accepting a first argument of type 'OAuthCreatingTicketContext' could be found (are you missing a using directive or an assembly reference?)
MusicStore\shared\Mocks\Google\TestGoogleEvents.cs(28,25): DNX,Version=v4.5.1 error CS1061: 'OAuthCreatingTicketContext' does not contain a definition for 'Principal' and no extension method 'Principal' accepting a first argument of type 'OAuthCreatingTicketContext' could be found (are you missing a using directive or an assembly reference?)
MusicStore\shared\Mocks\StartupOpenIdConnectTesting.cs(123,48): DNX,Version=v4.5.1 error CS1660: Cannot convert lambda expression to type 'OpenIdConnectOptions' because it is not a delegate type
MusicStore\shared\Mocks\Facebook\TestFacebookEvents.cs(18,25): DNX,Version=v4.5.1 error CS1061: 'OAuthCreatingTicketContext' does not contain a definition for 'Principal' and no extension method 'Principal' accepting a first argument of type 'OAuthCreatingTicketContext' could be found (are you missing a using directive or an assembly reference?)
MusicStore\shared\Mocks\Facebook\TestFacebookEvents.cs(29,25): DNX,Version=v4.5.1 error CS1061: 'OAuthCreatingTicketContext' does not contain a definition for 'Principal' and no extension method 'Principal' accepting a first argument of type 'OAuthCreatingTicketContext' could be found (are you missing a using directive or an assembly reference?)
MusicStore\shared\Mocks\StartupSocialTesting.cs(131,43): DNX,Version=v4.5.1 error CS1660: Cannot convert lambda expression to type 'FacebookOptions' because it is not a delegate type
MusicStore\shared\Mocks\StartupSocialTesting.cs(148,41): DNX,Version=v4.5.1 error CS1660: Cannot convert lambda expression to type 'GoogleOptions' because it is not a delegate type
MusicStore\shared\Mocks\StartupSocialTesting.cs(163,42): DNX,Version=v4.5.1 error CS1660: Cannot convert lambda expression to type 'TwitterOptions' because it is not a delegate type
MusicStore\shared\Mocks\StartupSocialTesting.cs(177,51): DNX,Version=v4.5.1 error CS1660: Cannot convert lambda expression to type 'MicrosoftAccountOptions' because it is not a delegate type

Building MusicStore for DNXCore,Version=v5.0
  Using Project dependency MusicStore 1.0.0-t160110222028
    Source: MusicStore\src\MusicStore\project.json

  Using Package dependency EntityFramework.Core 7.0.0-rc2-16705

Build failed.
    0 Warning(s)
```

If anyone could help me out, I would greatly appreciate it! 

Thank you,

Brian Abbott

**Comment by briancabbott** [comment]
Here is maybe a slightly more legible version:

MusicStore\src\MusicStore\StartupOpenIdConnect.cs(136,48): DNX,Version=v4.5.1 error CS1660: 
	Cannot convert lambda expression to type 'OpenIdConnectOptions' because it is not a delegate type
MusicStore\src\MusicStore\Startup.cs(165,43): DNX,Version=v4.5.1 error CS1660: 
	Cannot convert lambda expression to type 'FacebookOptions' because it is not a delegate type
MusicStore\src\MusicStore\Startup.cs(171,41): DNX,Version=v4.5.1 error CS1660: 
	Cannot convert lambda expression to type 'GoogleOptions' because it is not a delegate type
MusicStore\src\MusicStore\Startup.cs(177,42): DNX,Version=v4.5.1 error CS1660: 
	Cannot convert lambda expression to type 'TwitterOptions' because it is not a delegate type
MusicStore\src\MusicStore\Startup.cs(199,51): DNX,Version=v4.5.1 error CS1660: 
	Cannot convert lambda expression to type 'MicrosoftAccountOptions' because it is not a delegate type


MusicStore\shared\Mocks\MicrosoftAccount\TestMicrosoftAccountEvents.cs(18,25): DNX,Version=v4.5.1 error CS1061: 
	'OAuthCreatingTicketContext' does not contain a definition for 'Principal' and no extension method 'Principal' 
	accepting a first argument of type 'OAuthCreatingTicketContext' could be found (are you missing a using directive 
	or an assembly reference?)

MusicStore\shared\Mocks\MicrosoftAccount\TestMicrosoftAccountEvents.cs(29,25): DNX,Version=v4.5.1 error CS1061: 
	'OAuthCreatingTicketContext' does not contain a definition for 'Principal' and no extension method 'Principal' 
	accepting a first argument of type 'OAuthCreatingTicketContext' could be found (are you missing a using directive or an assembly reference?)
	
MusicStore\shared\Mocks\Google\TestGoogleEvents.cs(18,25): DNX,Version=v4.5.1 error CS1061: 
	'OAuthCreatingTicketContext' does not contain a definition for 'Principal' and no extension method 'Principal' 
	accepting a first argument of type 'OAuthCreatingTicketContext' could be found (are you missing a using directive or an assembly reference?)
	
MusicStore\shared\Mocks\Google\TestGoogleEvents.cs(28,25): DNX,Version=v4.5.1 error CS1061: 
	'OAuthCreatingTicketContext' does not contain a definition for 'Principal' and no extension method 'Principal' accepting a first argument of 
	type 'OAuthCreatingTicketContext' could be found (are you missing a using directive or an assembly reference?)
	
MusicStore\shared\Mocks\StartupOpenIdConnectTesting.cs(123,48): DNX,Version=v4.5.1 error CS1660: 
	Cannot convert lambda expression to type 'OpenIdConnectOptions' because it is not a delegate type
	
MusicStore\shared\Mocks\Facebook\TestFacebookEvents.cs(18,25): DNX,Version=v4.5.1 error CS1061: 
	'OAuthCreatingTicketContext' does not contain a definition for 'Principal' and no extension method 'Principal' 
	accepting a first argument of type 'OAuthCreatingTicketContext' could be found (are you missing a using directive or an assembly reference?)
	
MusicStore\shared\Mocks\Facebook\TestFacebookEvents.cs(29,25): DNX,Version=v4.5.1 error CS1061: 
	'OAuthCreatingTicketContext' does not contain a definition for 'Principal' and no extension method 'Principal' accepting a first argument of 
	type 'OAuthCreatingTicketContext' could be found (are you missing a using directive or an assembly reference?)
	
MusicStore\shared\Mocks\StartupSocialTesting.cs(131,43): DNX,Version=v4.5.1 error CS1660: 
	Cannot convert lambda expression to type 'FacebookOptions' because it is not a delegate type

MusicStore\shared\Mocks\StartupSocialTesting.cs(148,41): DNX,Version=v4.5.1 error CS1660: 
	Cannot convert lambda expression to type 'GoogleOptions' because it is not a delegate type

MusicStore\shared\Mocks\StartupSocialTesting.cs(163,42): DNX,Version=v4.5.1 error CS1660: 
	Cannot convert lambda expression to type 'TwitterOptions' because it is not a delegate type

MusicStore\shared\Mocks\StartupSocialTesting.cs(177,51): DNX,Version=v4.5.1 error CS1660: 
	Cannot convert lambda expression to type 'MicrosoftAccountOptions' because it is not a delegate type

Building MusicStore for DNXCore,Version=v5.0
  Using Project dependency MusicStore 1.0.0-t160110222028
    Source: MusicStore\src\MusicStore\project.json

  Using Package dependency EntityFramework.Core 7.0.0-rc2-16705

Build failed.
    0 Warning(s)

**Comment by briancabbott** [comment]
It looks like on the working extension methods, the second definition takes an Action<T> Delegate rather then just the object

Currently, 
IApplicationBuilder UseGoogleAuthentication(this IApplicationBuilder app, GoogleOptions options)


<member name="M:Microsoft.AspNet.Builder.FacebookAppBuilderExtensions
       .UseFacebookAuthentication(Microsoft.AspNet.Builder.IApplicationBuilder)">
   <summary>
   Adds the <see cref="T:Microsoft.AspNet.Authentication.Facebook.FacebookMiddleware"/>  middleware to the specified <see cref="T:Microsoft.AspNet.Builder.IApplicationBuilder"/>, which enables Facebook authentication capabilities.
   </summary>

<param name="app">The <see cref="T:Microsoft.AspNet.Builder.IApplicationBuilder"/> to add the middleware to.</param>
     <returns>A reference to this instance after the operation has completed.</returns>
      </member>
        
<member name="M:Microsoft.AspNet.Builder.FacebookAppBuilderExtensions.UseFacebookAuthentication(Microsoft.AspNet.Builder.IApplicationBuilder,Microsoft.AspNet.Builder.FacebookOptions)">
            <summary>
            Adds the <see cref="T:Microsoft.AspNet.Authentication.Facebook.FacebookMiddleware"/> middleware to the specified <see cref="T:Microsoft.AspNet.Builder.IApplicationBuilder"/>, which enables Facebook authentication capabilities.
            </summary>
            <param name="app">The <see cref="T:Microsoft.AspNet.Builder.IApplicationBuilder"/> to add the middleware to.</param>
            <param name="options">A <see cref="T:Microsoft.AspNet.Builder.FacebookOptions"/> that specifies options for the middleware.</param>
            <returns>A reference to this instance after the operation has completed.</returns>
        </member>

**Comment by Eilon** [comment]
I just re-cloned the repo and the build worked fine. Some tests failed, but I think that's more likely a setup issue on my machine.

**Comment by Eilon** [comment]
This sounds like a mismatch of builds between the DNX and the packages. Both the public build CI and internal build CI have been green (until a few days ago, when we just renamed everything and caused some breaks).
