### ISSUE TITLE
dnu restore -- fails to locate the NETStandard.Library

### ISSUE THREAD

**Issue by jonthegiant** [aspnet/MusicStore#592]
Executing `dnu restore` results in the error: `Unable to locate dependency Microsoft.dotnet.corehost`
This is because the NETStandard.Library hasn't been released on NuGet yet.

Adding
`<add key="DotNet-Core" value="https://myget.org/f/dotnet-core/api/v3/index.json" />`
to `NuGet.config` resolves the issue.

**Comment by natemcmaster** [comment]
There isn't really any actionable item here. We won't release this package on nuget until RC2. As you identified, the solution is to use pre-release package feeds.
