### ISSUE TITLE
Get tests working on Travis / Linux

### ISSUE THREAD

**Issue by dougbu** [aspnet/MusicStore#594]
MusicStore builds have been erroring or failing consistently on Travis for a while. Looks like the last successful Travis run was a month ago. (Admittedly, that span may include runs where Linux succeeded but OS X failed.)

The current issues occur during `Testing.SelfHostDeployer.StartSelfHost()` calls. May relate to aspnet/KestrelHttpServer#654 and look a bit similar to failures in aspnet/Entropy#102.

See failures in https://travis-ci.org/aspnet/MusicStore/jobs/111587838 for example.

**Comment by muratg** [comment]
@kichalla Could you please take a look?

**Comment by kichalla** [comment]
Build now passes on Travis.
