### ISSUE TITLE
It cannot be started from VS IDE.

### ISSUE THREAD

**Issue by xatabhk** [aspnet/MusicStore#595]
Only "dotnet run" works.

**Comment by Eilon** [comment]
@xatabhk we're working on an update to VS to better support this.

Though, I think with the latest changes as of yesterday this should open up in VS.

@kichalla can you confirm this?

**Comment by xatabhk** [comment]
About latest changes, I take you mean Microsoft.AspNetCore.Mvc.Dnx. Yes, it makes running Core applications in IDE work; but publishing from IDE is still broken.

**Comment by Eilon** [comment]
@xatabhk indeed, many things in the IDE will be non-functional until an update to VS is released.

**Comment by xatabhk** [comment]
I find IDE debugging is working again.
dnx:16595
dotnet:001840
