### ISSUE TITLE
Add build health badges to README.md

### ISSUE THREAD

**Issue by DavidObando** [aspnet/MusicStore#598]
We're building but I'd like to have a status badge.

## Travis

Travis:   [![Travis](https://travis-ci.org/aspnet/MusicStore.svg?branch=dev)](https://travis-ci.org/aspnet/MusicStore)

## Appveyor

AppVeyor: [![AppVeyor](https://ci.appveyor.com/api/projects/status/ja8a7j6jscj7k3xa/branch/dev?svg=true)](https://ci.appveyor.com/project/aspnetci/MusicStore/branch/dev)

**Comment by DavidObando** [comment]
@Eilon can you paste here the MusicStore badge from Appveyor? I don't have access to see it.

**Comment by Eilon** [comment]
The MusicStore id on AppVeyor is ja8a7j6jscj7k3xa.

**Comment by DavidObando** [comment]
@Eilon thanks!

**Comment by DavidObando** [comment]
Done.
