### ISSUE TITLE
We should make file strucuture and content as much same as possible between projectK musicstore and MVC musicstore

### ISSUE THREAD

**Issue by xqiu** [aspnet/MusicStore#6]
We should make file strucuture and content as much same as possible between projectK musicstore and MVCMusicstore.  So that I can easily do a windiff to see the difference, and easily design tool for migration

Right now, it's hard to read the differences between two apps.  Especially:
1. K musicstore doesn't have a app_start folder
2. Controller's don't even perform the same actions  (is this because MVCMusicStore is not updated as musicstore received update recently?)

Please take consideration

**Comment by Praburaj** [comment]
Some of these changes cannot be avoided and it has been kept similar to the previous version in possible places.
