### ISSUE TITLE
Identity cookie name is set incorrectly

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/MusicStore#602]
We expecting the cookie name for identity to be `".AspNetCore.Identity.Application"` but actually getting `".AspNetCore..AspNetCore.Identity.Application"`. Is this a bug in how Music Store is configured or in Identity?

cc @kichalla @JunTaoLuo

**Comment by JunTaoLuo** [comment]
Probably an issue in Identity. I'll take a look

**Comment by JunTaoLuo** [comment]
Moving this issue to https://github.com/aspnet/Identity/issues/763
