### ISSUE TITLE
"netstandardapp1.5" is an unsupported framework.

### ISSUE THREAD

**Issue by sonealtx** [aspnet/MusicStore#607]
Hi, I'm trying to run the project in Visual Studio 2015, and I'm getting this error in project.json:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1008	"netstandardapp1.5" is an unsupported framework.	MusicStore	C:\Users\Seth\Documents\Visual Studio 2015\Projects\MusicStore-dev\src\MusicStore\project.json	60	

I'm not sure how to get past this error.
Thanks in advance for any help.

**Comment by davidfowl** [comment]
Use the master branch.

**Comment by sonealtx** [comment]
thanks!

**Comment by friism** [comment]
@davidfowl If `dev` doesn't work, should the default app for this repo be `master`?

**Comment by Eilon** [comment]
`master` is the latest released, but `dev` is the one with active development, so we keep that as the default.
