### ISSUE TITLE
Make the repo build without the src folder

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/MusicStore#612]
On the CI we want to run tests without src. Tests will get recompiled but the product will be restored from packages.

Once you fix this, please update `KOREBUILD_NOSRC_EXCLUDE` on the CI

**Comment by Eilon** [comment]
@victorhurdugaci any chance you'll have time for this?

**Comment by victorhurdugaci** [comment]
Unfortunately, this is not possible.The tests require the source code to deploy because we never save published apps anywhere. I think we should see MusicStore as `sample` rather than `src`. In that case, it makes sense to always have the source code.
