### ISSUE TITLE
Want a sample that not use EF

### ISSUE THREAD

**Issue by John0King** [aspnet/MusicStore#615]
EF is great, but  some times we might can not use EF, is there a sample that use raw sql?

**Comment by Eilon** [comment]
Not planning on such a sample at this time.

**Comment by hbrock** [comment]
I could write a sample using Dapper.

**Comment by Eilon** [comment]
If folks have alternative versions of MusicStore that they want to make, we could certainly link to them from the readme of this repo.

**Comment by John0King** [comment]
@hbrock  there is a link ?

**Comment by hbrock** [comment]
@John0King 
I said I could. I have not yet did it.

**Comment by Eilon** [comment]
No plans to change this in the Music Store test app. If you have a sample you'd like to link to, please send a PR with a change to the readme.md file. Thanks!
