### ISSUE TITLE
[question] dependencies on issue on build

### ISSUE THREAD

**Issue by nerradchoong** [aspnet/MusicStore#616]
"Microsoft.Extensions.Configuration.CommandLine": "1.0.0-*",
"Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0-*",

The dependency Microsoft.Extensions.Configuration.CommandLine 1.0.0-rc2-200270 in project MusicStore.Test does not support framework .NETFramework,Version=v4.5.1

how do you guys solve this?

**Comment by Eilon** [comment]
@kichalla any idea?

**Comment by kichalla** [comment]
Since its been a while we had a coherence build, building `dev` with existing coherence packages is probably not guaranteed to work.

**Comment by cevarief** [comment]
I've also got too many dependencies error both using dx 451 and 50.

Unable to resolve dependency Microsoft.AspNetCore.Authentication.Cookies 1.0.0-rc2-20320
Unable to resolve dependency Microsoft.AspNetCore.Authentication.Facebook 1.0.0-rc2-20320
Unable to resolve dependency Microsoft.AspNetCore.Authentication.Google 1.0.0-rc2-20320
Unable to resolve dependency Microsoft.AspNetCore.Authentication.MicrosoftAccount 1.0.0-rc2-20320
Unable to resolve dependency Microsoft.AspNetCore.Authentication.OpenIdConnect 0.1.0-rc2-20320
Unable to resolve dependency Microsoft.AspNetCore.Authentication.Twitter 1.0.0-rc2-20320
...

**Comment by kichalla** [comment]
This should be fixed now. Make sure to delete the `.build` folder or (do `git clean -xdf` if you are using `git`) and then kick start the build.

Feel free to re-open the issue with more details.
