### ISSUE TITLE
MusicStore app consumes 50% of CPU with just one single client.

### ISSUE THREAD

**Issue by sivagms** [aspnet/MusicStore#623]
Azure standard A2 machine
Investigate the cpu profile to see what are the culprits..
/CC @SajayAntony

**Comment by martinpf** [comment]
PerfView shows 40% of MusicStore CPU in EntityFramework and 70% in async libraries.   Looks like the cost of iterating through query results is high

**Comment by anpete** [comment]
Fixed in fb4fadb0b10 - @Eilon ok to close?

**Comment by Eilon** [comment]
Ah, of course, yes.

**Comment by sivagms** [comment]
now we are able to get 114 req/sec (compared to < 1 req/sec before the fix)

**Comment by Eilon** [comment]
I'll take a 10,000% improvement any day of the week 😄
