### ISSUE TITLE
Re-enable tests skipped due to CoreFX bug

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/MusicStore#627]
Revert the changes in https://github.com/aspnet/MusicStore/commit/a3b959a02837fe413987cd513a8d2439d42f05a7 once we have the CoreFX fix for https://github.com/dotnet/corefx/issues/7440

**Comment by BrennanConroy** [comment]
This can be reverted now

**Comment by JunTaoLuo** [comment]
Had to redisable these tests in https://github.com/aspnet/MusicStore/pull/659. Reopening this issue to track enabling of these tests after we have an updated cli.

**Comment by Eilon** [comment]
@JunTaoLuo perhaps we can verify this again today? We should have fairly recent CoreFX's already, and today we've taken an even newer one.

**Comment by JunTaoLuo** [comment]
@Eilon already doing that. There seems to be another problem, I'm verifying whether that is an issue with CoreFX.

**Comment by Eilon** [comment]
Thanks!

**Comment by JunTaoLuo** [comment]
blocked on https://github.com/dotnet/corefx/issues/8941

**Comment by stephentoub** [comment]
@JunTaoLuo, can you try https://github.com/dotnet/corefx/pull/8946?

**Comment by JunTaoLuo** [comment]
@stephentoub How do I test out your fix in the linked PR? Will you build a package for me to test?

**Comment by stephentoub** [comment]
> How do I test out your fix in the linked PR? 

You can build System.Net.Http.dll from my branch and overwrite the one in your published directory.  If you don't want to build it yourself, I've emailed you a build you can use.

**Comment by JunTaoLuo** [comment]
@stephentoub Thanks, I verified this has fixed the issue we are running into.

**Comment by JunTaoLuo** [comment]
tests enabled after we received the fixes in https://github.com/dotnet/corefx/pull/9282
