### ISSUE TITLE
Music store needs to be able to use shared runtime. 

### ISSUE THREAD

**Issue by SajayAntony** [aspnet/MusicStore#631]
/cc @muratg @davidfowl

**Comment by muratg** [comment]
@NTaylorMullen @pranavkm @pakrym

**Comment by muratg** [comment]
(Also tracked here for the changes across the repos: https://github.com/aspnet/Coherence-Signed/issues/202)

**Comment by Eilon** [comment]
Is this already done? There's MusicStore and MusicStore.Standalone:

* https://github.com/aspnet/MusicStore/blob/dev/src/MusicStore/project.json
* https://github.com/aspnet/MusicStore/blob/dev/src/MusicStore.Standalone/project.json

**Comment by muratg** [comment]
Yes, this was done with https://github.com/aspnet/MusicStore/pull/645
