### ISSUE TITLE
Make queries no-tracking by default

### ISSUE THREAD

**Issue by anpete** [aspnet/MusicStore#639]

**Comment by Eilon** [comment]
@anpete, a gift for you.

**Comment by anpete** [comment]
@Eilon you shouldn't have

**Comment by Eilon** [comment]
I'll get you an ice cream 🍦

**Comment by DamianEdwards** [comment]
ping @anpete @ajcvickers

**Comment by Eilon** [comment]
Moving to 2.1.0.

**Comment by mkArtakMSFT** [comment]
Closing this issue as there was no community involvement for quite a while now.
