### ISSUE TITLE
Show test progress when running functional tests

### ISSUE THREAD

**Issue by kichalla** [aspnet/MusicStore#642]
Currently when functional tests run there is not much output shown on the screen giving the users the impression that the tests are in hung state and users tend to kill the process.

I agree that the current experience is better compared to earlier one where we used to write bunch of log output statements and was not user friendly. Currently we show the detailed output only when the test fails which is great.

We should see if we can balance this experience so that we write minimal output to show the progress of tests and still show the detailed info only when the tests fail.

cc @natemcmaster

**Comment by natemcmaster** [comment]
Yes, xunit swallows the E2E tests logger so individual test output can be isolated. `dotnet test -verbose`? This will show you when a test has started.

Alternatively, you could add scatter a few lines of `Console.WriteLine("ping: don't worry, I'm still running!")` into the tests.

**Comment by Eilon** [comment]
Yeah I'd be fine with just some `Console.WriteLine()`s scattered about. Pretty cheap and easy fix. But if there's some nicer way that's also cheap we could do that instead.
