### ISSUE TITLE
Fix project.json file trailing comma

### ISSUE THREAD

**Issue by Eilon** [aspnet/MusicStore#652]
This is broken in `dev` and `release`.

https://github.com/aspnet/MusicStore/blob/dev/src/MusicStore/project.json#L53

@kichalla can you fix this ASAP for RC2, then port to RTM? You're approved.

**Comment by kichalla** [comment]
Sure

**Comment by kichalla** [comment]
f7d5a1faf24a3e8cbdc9b180a6d2b38e4963f6f4

**Comment by Eilon** [comment]
Thanks, that was fast! 😄
