### ISSUE TITLE
MusicStore failures on Nano

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/MusicStore#658]
The way we are determining whether we are running on Nano is out of date. We currently look for the product type defined by [Platform.cs#L10](https://github.com/aspnet/MusicStore/blob/dev/src/MusicStore/Platform.cs#L10) via calls to `GetProductInfo`. However, according to newer versions of `winnt.h` used by Nano TP5, there are some new product types:

```
#define PRODUCT_NANO_SERVER                         0x0000006D
...
#define PRODUCT_DATACENTER_NANO_SERVER              0x0000008F  
#define PRODUCT_STANDARD_NANO_SERVER                0x00000090 
```
For our code to work, we need to recognize all three products as nano server.

The impact of this mismatch is that music store will fail to run on some versions of Nano Server and cause test failures if we run them. We currently rely on this differentiation to determine what type of database to use, in-memory vs SQL, for example.

We should fix this in rtm, but possibly consider rc2 as well since it's a small change. Thoughts? cc @victorhurdugaci @muratg @Eilon 

I also feel that this is the wrong place to have this logic. PlatformAbstractions looks like a better place to move to long term? But if we are only using it once in this repo, I guess that's not a big deal.

**Comment by victorhurdugaci** [comment]
So, without this change, MusicStore doesn't work out of the box on Nano TP5 because it incorrectly determines that it's not running on Nano

**Comment by muratg** [comment]
I'm OK getting this in RC2 as long as @Eilon is fine. Otherwise a dev branch check-in only is fine.

**Comment by Eilon** [comment]
It's a MusicStore-only fix, so let's do in RC2.
