### ISSUE TITLE
Move "Microsoft.NETCore.Platforms" under "net451" in project.json

### ISSUE THREAD

**Issue by mikeharder** [aspnet/MusicStore#665]
Project.json currently has `Microsoft.NETCore.Platforms` under the global `dependencies`.  It should be moved under the `net451` framework, since I believe it's only required for `net451`, and it breaks `dotnet restore` if you convert to standalone and target a non-Windows RID like `debian.8-x64`:

```
Errors in D:\Git\MusicStore\src\MusicStore\project.json
    System.AppContext 4.1.0-rc2-24027 provides a compile-time reference assembly for System.AppContext on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with debian.8-x64.
    System.Runtime.InteropServices.RuntimeInformation 4.0.0-rc2-24027 provides a compile-time reference assembly for System.Runtime.InteropServices.RuntimeInformation on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible
 with debian.8-x64.
    One or more packages are incompatible with .NETCoreApp,Version=v1.0 (debian.8-x64).
```

**Comment by Eilon** [comment]
Hmm is that the standard guidance that we give for where to locate this dependency? MusicStore should do whatever our recommendation is, though I admit I don't know what that is.

@anurse @davidfowl @JunTaoLuo ?

**Comment by JunTaoLuo** [comment]
To summarize our offline discussion this afternoon, currently we have `Microsoft.NETCore.Platforms` under global `dependencies` in our repos. However, if it is causing trouble, it can be moved to `net451` TFM where we needed it to resolve rids. For `netcoreapp1.0`, the `Platforms` package is brought in transitively via `Microsoft.NETCore.App`. Note that this is a point in time problem since, IIRC, we plan to have placeholder runtime dlls that will resolve the issue when compiling against some system packages on `net451`. Eventually we won't need this dependency at all. @davidfowl, do you remember which packages were causing problems and whether they have been updated yet?

**Comment by davidfowl** [comment]
I don't understand why it's broken, it always required for all frameworks in general. It's included with `Microsoft.NETCore.App` and `NETStandard.Library`. It's required for any native dependencies. In RTM it'll just be a dependency of the https://github.com/aspnet/libuv-package/pull/6

**Comment by JunTaoLuo** [comment]
Hmm that's true, both TFMs should be bringing in the same version of `NETCore.Platforms`. In fact, now I'm not sure why brining the `NETCore.Platforms` dependency under `net451` fixes the restore errors. Unless `NETCore.App` is brining in a different version of `NETCore.Platforms`? Need to look at the lock file more thoroughly.

**Comment by Eilon** [comment]
@JunTaoLuo I'm assigning to you to investigate because I want to make sure there isn't some more severe issue here. I don't *think* we want to move the location of the reference, so if it's not working somewhere for some reason, we should find out why and report that to the proper authorities.

**Comment by mikeharder** [comment]
There's definitely a real issue here, since the current `project.json` breaks `dotnet restore` if you convert to standalone and target a non-Windows RID.  It might be a bug in CLI/CoreFX.  We should be able to create a minimal repro.

**Comment by Eilon** [comment]
If we have a minimal repro please log a bug in CLI.

**Comment by Eilon** [comment]
(Assuming that that's where the bug appears to be.)

**Comment by JunTaoLuo** [comment]
I can no longer reproduce this error and @mikeharder and I agree that there is nothing inside MusicStore that needs to be fixed. Closing.

**Comment by Eilon** [comment]
Thanks!
