### ISSUE TITLE
Header links are broken in Admin area

### ISSUE THREAD

**Issue by mikeharder** [aspnet/MusicStore#666]
**Repro Steps**
1. Browse to MusicStore
2. Login as admin
3. Click `admin` link in footer
4. Click header link like `Home`

**Expected**
1. Link target is `/`.

**Actual**
1. Link target is `/Admin/Home`, which redirects to `/Home/StatusCodePage` and displays the error `Item not found`.
2. Clicking the `Home` link again (when on the error page) works correctly.

**Comment by hbrock** [comment]
Is anyone working on this? If not I would like to create a fork and submit a pull request.

**Comment by Eilon** [comment]
Sorry, I forgot to mark this as `up-for-grabs`. If you submit a PR, we'll definitely have a look!

**Comment by kichalla** [comment]
Fixed by 1bce0acfde5b9fe5e5e48b6311bdfb232cdbf444
