### ISSUE TITLE
Cache of "topselling" items should be invalidated when an album is removed

### ISSUE THREAD

**Issue by mikeharder** [aspnet/MusicStore#669]
## Repro Steps
1. Launch MusicStore
2. Login as admin
3. Remove topselling album, such as `The Best Of The Men At Work`
4. Refresh homepage
## Expected

Removed album does not appear on homepage
## Actual

Removed album appears on homepage, but clicking it causes an `Item not found` error.

**Comment by mkArtakMSFT** [comment]
Closing this issue as there was no community involvement for quite a while now.
