### ISSUE TITLE
Cannot Log off in /Admin/StoreManager

### ISSUE THREAD

**Issue by WilliamWsyHK** [aspnet/MusicStore#680]
1. Login
2. Navigate to `/Admin/StoreManager`
3. Click Log off
4. You should be navigated to `/Home/StatusCodePage`, which reads _**Item not found**_

**Comment by Eilon** [comment]
@kichalla assigning to you because I assigned PR https://github.com/aspnet/MusicStore/pull/675 to you to merge.

**Comment by kichalla** [comment]
Fixed by 1bce0acfde5b9fe5e5e48b6311bdfb232cdbf444
