### ISSUE TITLE
Consider explicit version numbers in release version

### ISSUE THREAD

**Issue by cartermp** [aspnet/MusicStore#681]
The current `project.json` files in the release branch use a splat (`*`) string in all the package dependencies.  This causes restore errors because packages that aren't guaranteed to be compatible with RC2 are pulled down.

**Comment by Eilon** [comment]
@cartermp we actually already do this, but only in certain branches/tags.

For example, the `master` branch always points at the latest version that's on NuGet, so you'll see only `1.0.0` versions in https://github.com/aspnet/MusicStore/blob/master/src/MusicStore/project.json.

And then each release also has a Git tag, which you can go to, and the exact version numbers are burned in there as well:
![musicstore-tags](https://cloud.githubusercontent.com/assets/202643/16460274/77eb40f6-3ddb-11e6-8952-6fe92fc0de20.png)
