### ISSUE TITLE
Make it easier to use in-memory store if SQL is not available

### ISSUE THREAD

**Issue by mikeharder** [aspnet/MusicStore#689]
Currently, MusicStore assumes that SQL is available when running on full Windows (it uses the in-memory store on non-Windows, Mono, and Nano Server).  This causes problems when running MusicStore on full Windows without SQL, since it hangs for many seconds before finally displaying a SQL error.  A common scenario is running MusicStore on a Windows Server container without SQL.

We should make one of the following improvements:
1. `Platform.UseInMemoryStore` should check for what it actually needs (SQL Server), rather than assume SQL is installed on Windows.  This way, MusicStore would "just work" on Windows without SQL.
2. Add an environment variable to control whether MusicStore uses SQL or in-memory.  This would be easy to set in a Windows Container dockerfile.

**Comment by mkArtakMSFT** [comment]
Closing this issue as there was no community involvement for quite a while now.
