### ISSUE TITLE
VS2015 incompatible problem

### ISSUE THREAD

**Issue by pumaatlarge** [aspnet/MusicStore#698]
Actually, I am using VS 2015 version 14.0.23107.0 D14REL
After opening the solution, is showed "This project is incompatible with the current Visual Sudio", what's wrong? Any special edition needed?

**Comment by KostaVlev** [comment]
In order to open .NET Core project you need to install Update 3 for Visual Studio.

[https://www.microsoft.com/net/core#windows](.NET Core)

**Comment by pumaatlarge** [comment]
After installing update 3, the incompatible problems solved, but it now showed errors on E2ETest.xproj, MusicStore.xproj, MusicStore.Test.xproj, and MusicStore.Standalone.xproj. It siad  " Microsoft.DotNet.targets"  and " Microsoft.DotNet.Prop" was not found.

**Comment by pumaatlarge** [comment]
Everything is ok after reinstalling VS15 and patces
