### ISSUE TITLE
Please add PostgreSQL support

### ISSUE THREAD

**Issue by JanSichula** [aspnet/MusicStore#710]
May I kindly suggest that you add support for PostgreSQL. This way, this referential solution will be truly cross-platform and not dependent directly on MS SQL and indirectly on Windows. There are folks out there who are excited about ASP.NET Core and yet would like to avoid any lock-in into closed source proprietary databases.

**Comment by Eilon** [comment]
See explanation here: https://github.com/aspnet/MusicStore/pull/730#issuecomment-267112052
