### ISSUE TITLE
Can not find compilation library location for package 'microsoft.csharp'

### ISSUE THREAD

**Issue by xatabhk** [aspnet/MusicStore#712]
![reference_not_found](https://cloud.githubusercontent.com/assets/6814395/19185766/a28321a2-8cb5-11e6-9370-182923bdeb5c.png)
Here are the error messages:
[error.txt](https://github.com/aspnet/MusicStore/files/515757/error.txt)

**Comment by Eilon** [comment]
Closing because we believe this issue has been fixed.
