### ISSUE TITLE
Clean up README.md

### ISSUE THREAD

**Issue by pranavkm** [aspnet/MusicStore#715]
The README page for MusicStore is pretty outdated and references things we no longer ship (Helios, DNX etc).

**Comment by pranavkm** [comment]
@kichalla, is this accurate: From the README:

> NOTE: App and tests require Visual Studio 2015 LocalDB on the machine to run.

**Comment by kichalla** [comment]
Cleaned up in commits : 2b68a00da344dc0aae215ff83ee13b24ca0a8834 and bf7eaa166c91ea88cc636e53069ace6b21df0fe8
