### ISSUE TITLE
admin password

### ISSUE THREAD

**Issue by eliassal** [aspnet/MusicStore#722]
I managed to have the site up and running with docker. Can you please let me know what is the password for admin user, I saw in the tables a user with the email
Administrator@test.com
but can noit see what is the password

**Comment by vladoATL** [comment]
"DefaultAdminUsername": "Administrator@test.com",
  "DefaultAdminPassword": "YouShouldChangeThisPassword1!",

**Comment by eliassal** [comment]
Thanks
