### ISSUE TITLE
unable to start debugging.

### ISSUE THREAD

**Issue by freerider7777** [aspnet/MusicStore#728]
I downloaded the project, opened in VS 2015 update 3. Music store and Musicstore.Standalone do not run - Unable to start debugging. (BTW 1.2 packages seem strange, no?)

**Comment by omerv2** [comment]
What is the exact error that you get?

**Comment by freerider7777** [comment]
Now it's ok (after your global.json change)
Now MusicStore starts ok, MusicStore.Standalone does not find config.json (Exception)

**Comment by Eilon** [comment]
@kichalla have you seen any issues in MusicStore or MusicStore.Standalone?

**Comment by kichalla** [comment]
Fixed with commit ecdc864e4f462712bc82d8f365cf9108092feb0b
