### ISSUE TITLE
not using IDistributedCache

### ISSUE THREAD

**Issue by freerider7777** [aspnet/MusicStore#729]
Why do you use services.AddDistributedMemoryCache() if not using IDistributedCache?

**Comment by Eilon** [comment]
Hi @freerider7777 , the session state feature requires an implementation of IDistributedCache. Session state is used to track the user's shopping cart id: https://github.com/aspnet/MusicStore/blob/dev/samples/MusicStore/Models/ShoppingCart.cs#L171
