### ISSUE TITLE
Unable to load solution in VS2015

### ISSUE THREAD

**Issue by sneh1** [aspnet/MusicStore#733]
I get the following error when I click and open the MusicStore.sln. Please help me fix it. 

MusicStore\test\E2ETests\E2ETests.xproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

**Comment by natemcmaster** [comment]
Closing as this project has been upgraded to VS 2017. You can get VS 2017 RC from https://visualstudio.com.
