### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by easec** [aspnet/MusicStore#735]
Hi there! Get a lot of compiling errors when I tried these on Windows Server 2016 Datacenter with latest Docker and Docker-Compose. Running the server in nested virtualization.

![error](https://cloud.githubusercontent.com/assets/23214234/22023981/c6e5f0b6-dcc8-11e6-8c0b-b4e8cdc349a9.png)

Any suggestions?

**Comment by natemcmaster** [comment]
Compiling this repo in Docker isn't supported. We've decided to remove the docker files. See #812.
