### ISSUE TITLE
Does no building with new core version 

### ISSUE THREAD

**Issue by reypila** [aspnet/MusicStore#738]
This example have a lot problems with compatibility , the problem is in project.json

**Comment by ginoway** [comment]
had the same problems with compatibility. to resolve with[ .net core sdk rc4](https://github.com/dotnet/core/tree/master/release-notes)

and then Build succeeded.  

> dotnet restore
> dotnet build --framework {targetFramework Option}, 

hope it useful.

**Comment by Eilon** [comment]
The project seems to be building fine on Windows/Mac/Linux. Please check that you have the latest 'dev' branch.
