### ISSUE TITLE
Use the runtime store in MusicStore at the end of the build chain

### ISSUE THREAD

**Issue by pranavkm** [aspnet/MusicStore#757]
Would be important to verify scenarios like (https://github.com/aspnet/Mvc/issues/5690) work E2E when Mvc is referenced via a metapackage.

**Comment by Eilon** [comment]
@pranavkm I assume you mean Microsoft.AspNetCore.All? https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.AspNetCore.All

**Comment by kichalla** [comment]
We now have tests in CI using the runtime store.
