### ISSUE TITLE
Error RuntimeIdentifier must be set for .NETFramework executables.

### ISSUE THREAD

**Issue by hazemusa** [aspnet/MusicStore#760]
I am trying to use the MusicStore to learn. I have VS2017 RC and when I build, I get:

Error RuntimeIdentifier must be set for .NETFramework executables.
Consider RuntimeIdentifier=win7-x86 or RuntimeIdentifier=win7-x64. MusicStore C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.RuntimeIdentifierInference.targets

Here is my .targets file:
$(MSBuildAllProjects);$(MSBuildThisFileFullPath)

<When Condition="$(RuntimeIdentifier.EndsWith('-x86')) or $(RuntimeIdentifier.Contains('-x86-'))">
  <PropertyGroup>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
</When>

<When Condition="$(RuntimeIdentifier.EndsWith('-x64')) or $(RuntimeIdentifier.Contains('-x64-'))">
  <PropertyGroup>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
</When>

<When Condition="$(RuntimeIdentifier.EndsWith('-arm')) or $(RuntimeIdentifier.Contains('-arm-'))">
  <PropertyGroup>
    <PlatformTarget>arm</PlatformTarget>
  </PropertyGroup>
</When>

<Otherwise>
  <PropertyGroup>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
</Otherwise>

false $(IntermediateOutputPath)$(RuntimeIdentifier)\ $(OutputPath)$(RuntimeIdentifier)\

**Comment by pranavkm** [comment]
The issue you were running in to was fixed as part of VS RTM. Go ahead and grab it from https://www.visualstudio.com/downloads/. I'd also recommend using the tutorials on https://docs.microsoft.com/en-us/aspnet/core/. MusicStore is primarily meant for E2E testing the AspNetCore stack so it does things that are atypical of most applications.

**Comment by hazemusa** [comment]
Thank you!

It is working now based on your suggestion
