### ISSUE TITLE
Skip standalone tests temporarily

### ISSUE THREAD

**Issue by kichalla** [aspnet/MusicStore#761]
Following is the error that I see when running standalone tests on Ubuntu 16.04 LTS.
![image](https://cloud.githubusercontent.com/assets/6559784/24063265/3868b666-0b1c-11e7-961b-ec71335ff165.png)

https://github.com/aspnet/MusicStore/commit/fcb4b6ddbcc0b7a50cd9292bfff14e0b2e354810

@pranavkm

**Comment by pranavkm** [comment]
Didn't it fail the same way on OSX too?

**Comment by JunTaoLuo** [comment]
Yup, these failures started to happen on *nix once we switched to 2.0 CLI it seems.

**Comment by kichalla** [comment]
https://github.com/dotnet/cli/issues/6286

**Comment by JunTaoLuo** [comment]
Is it possible to do chmod +x before trying to start the app?

**Comment by kichalla** [comment]
e606844509b412d72c6dbd40b1b0a4a73754943a
