### ISSUE TITLE
Investigate System.Security.Claims references required to make compilation work

### ISSUE THREAD

**Issue by pranavkm** [aspnet/MusicStore#763]
https://github.com/aspnet/MusicStore/commit/90acbd1e62e690a44196db43065843811839c47c

**Comment by pranavkm** [comment]
Also `System.Globalization.Extensions` -  https://github.com/aspnet/MusicStore/commit/51e84a623c658e27e6e1b0717749981cb2ad8bac

**Comment by Eilon** [comment]
@pranavkm says this should be fine now, so we should be able to remove the explicit package references.
