### ISSUE TITLE
SmokeTests flaky on CI

### ISSUE THREAD

**Issue by jbagga** [aspnet/MusicStore#767]
[SmokeTestsOnNanoServerUsingSharedRuntime.Test](http://aspnetci/viewLog.html?buildId=192835&tab=buildResultsDiv&buildTypeId=XPlat_Windows_WinNanoServer_MusicStore) are flaky.

For applicationType Portable the exception is `One or more errors occurred. (Access to the path '\\projectk-nano\musicstore\dotnet\dotnet.exe' is denied.) (The following constructor parameters did not have matching fixture data: DotnetRuntimeSetupTestFixture dotnetRuntimeSetupTestFixture)`

For applicationType Standalone the exception is 
```
Assert.Equal() Failure
Expected: OK
Actual:   InternalServerError
```
cc @kichalla @Tratcher

**Comment by kichalla** [comment]
This is fixed. This started happening after a build was killed leaving resources (port) not being cleaned resulting in later test runs to fail when trying to listen on same port.
