### ISSUE TITLE
Powershell doesn't exist in the Dockerfile base image

### ISSUE THREAD

**Issue by devinvisible** [aspnet/MusicStore#776]
The SHELL instruction specifies powershell but the base image doesn't have it available. 
(Solution 1) Perhaps the intention was to use the `-nanoserver` flavor?

In fact, I wonder if powershell is really necessary here. It's used for one command (`RUN New-Item -Path \MusicStore\samples\MusicStore -Type Directory`) which isn't even actually necessary - the WORKDIR and ADD instructions both create directories if they don't already exist.
(Solution 2) Remove the RUN New-Item line

**Comment by natemcmaster** [comment]
We've decided to remove the Dockerfiles from this repo as building MusicStore in Docker is not supported. See #812.
