### ISSUE TITLE
Dockerfile.windows uses a deprecated base image

### ISSUE THREAD

**Issue by devinvisible** [aspnet/MusicStore#777]
From https://blogs.msdn.microsoft.com/dotnet/2017/03/07/announcing-net-core-tools-1-0/#docker

> We adopted changes to the Docker tag scheme we use at microsoft/dotnet. The “-projectjson” and “-msbuild” differentiation is now gone. The tags are significantly simpler, as you can see from the tags above.

**Comment by natemcmaster** [comment]
Closing as we have removed dockerfiles from this repo. See #812 for more details.
