### ISSUE TITLE
Error docker-compose build 

### ISSUE THREAD

**Issue by takekazuomi** [aspnet/MusicStore#794]
"Docker-compose build" fails.

## Reproduction procedure
```
$ docker-compose -f .\docker-compose.windows.yml build
db uses an image, skipping
Building web
Step 1/12 : FROM microsoft/dotnet:1.1-sdk-msbuild
1.1-sdk-msbuild: Pulling from microsoft/dotnet
ERROR: Service 'web' failed to build: image operating system "linux" cannot be used on this platform
```

## Problem
1.  Dockerfile.windows use old image.  https://github.com/aspnet/MusicStore/issues/777
2.  Dockerfile.windows use dotnet sdk 1.1 but Music Store app use 2.0.

**Comment by natemcmaster** [comment]
Closing as we have removed dockerfiles from this repo. See #812 for more details.
