### ISSUE TITLE
Build Error on the Latest

### ISSUE THREAD

**Issue by johntallon** [aspnet/MusicStore#799]
Hi, 

I forked and trying to build and getting a build error: 

'WebListenerOptions' does not contain a definition for 'Listener' and no extension method 'Listener' accepting a first argument of type 'WebListenerOptions' could be found (are you missing a using directive or an assembly reference?) [...\Sample Music Store\src\MusicStore\MusicStore.csproj]

Can package am I missing?

**Comment by natemcmaster** [comment]
@johntallon most likely, you need to pull the latest changes from the dev branch into your fork and try again. WebListenerOptions is an old API that does not exist anymore.

See https://github.com/aspnet/MusicStore/commit/cd5a789b2b1ae6ad5fff04b5b518cbcb7314a6e6.
