### ISSUE TITLE
Smoke test fails to login with Google

### ISSUE THREAD

**Issue by svick** [aspnet/MusicStore#802]
When I run an E2E smoke test on my machine, the test fails when trying to login with Google.

Specifically, the failure is (truncated):

> Test Name:	E2ETests.SmokeTests_X64.WindowsOS(serverType: Kestrel, architecture: x64, applicationType: Portable)
Test FullName:	E2ETests.SmokeTests_X64.WindowsOS (c54ac54dac7f1e92fff5efff88317a1ccbd90d2e)
Test Source:	 : line 0
Test Outcome:	Failed
Test Duration:	0:02:00,797
>
> Result StackTrace:	
at E2ETests.Validator.<LoginWithGoogle>d__1.MoveNext() in E:\Users\Svick\git\aspnet-MusicStore\test\MusicStore.E2ETests\Implementation\GoogleLoginScenarios.cs:line 44
…
Result Message:	Assert.NotEmpty() Failure
Result StandardOutput:	
…
| SmokeTestSuite Information: Signing in with Google account
| SmokeTestSuite Information: POST Account/ExternalLogin
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Request starting HTTP/1.1 POST http\://localhost:8577/Account/ExternalLogin application/x-www-form-urlencoded 212
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Executing action method MusicStore.Controllers.AccountController.ExternalLogin (MusicStore) with arguments (Google, /) - ModelState is Valid
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: info: Microsoft.AspNetCore.Mvc.ChallengeResult[1]
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Executing ChallengeResult with authentication schemes (Google).
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: info: Microsoft.AspNetCore.Authentication.Google.GoogleHandler[12]
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       AuthenticationScheme: Google was challenged.
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Executed action MusicStore.Controllers.AccountController.ExternalLogin (MusicStore) in 312.1284ms
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:       Request finished in 315.8831ms 302 
| SmokeTestSuite Information: Request headers: 
| SmokeTestSuite Information: Response headers: Date=Mon, 19 Jun 2017 23:41:44 GMT
|                             Location=https\://accounts.google.com/o/oauth2/auth?response_type=code&client_id=%5BClientId%5D&redirect_uri=http%3A%2F%2Flocalhost%3A8577%2Fsignin-google&scope=openid%20profile%20email&access_type=offline&state=ValidStateData&custom_redirect_uri=custom
|                             Server=Kestrel
|                             Set-Cookie=.AspNetCore.Correlation.Google.ED0UbsdJ5f0i480ND6rJz8b8M8hZydFmV6C5fy292eY=N; expires=Mon, 19 Jun 2017 23:56:44 GMT; path=/signin-google; httponly
| Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Attempting to cancel process 145992
…

Likely related: when I debug the test, the following exception is thrown (and caught):

> System.Net.CookieException: 'An error occurred when parsing the Cookie header for Uri 'http\://localhost:8861/Account/ExternalLogin'.'
> StackTrace:
   at System.Net.CookieContainer.CookieCutter(Uri uri, String headerName, String setCookieHeader, Boolean isThrow)
> Inner Exception:
> CookieException: The 'Path'='/signin-google' part of the cookie is invalid.
> StackTrace:
    at System.Net.Cookie.VerifySetDefaults(CookieVariant variant, Uri uri, Boolean isLocalDomain, String localDomain, Boolean setDefault, Boolean shouldThrow)
   at System.Net.CookieContainer.CookieCutter(Uri uri, String headerName, String setCookieHeader, Boolean isThrow)

**Comment by kichalla** [comment]
fc56105d833198421fc16fb1d9e0f13eacffcddb
