### ISSUE TITLE
Flaky tests: SmokeTests_X64 and NtlmAuthenticationTests

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/MusicStore#825]
The following tests are failing on CI:

NtlmAuthenticationTests.NtlmAuthenticationTest_IISExpress_CLR
NtlmAuthenticationTests.NtlmAuthenticationTest_IISExpress_CoreCLR_Portable
NtlmAuthenticationTests.NtlmAuthenticationTest_IISExpress_CoreCLR_Standalone
SmokeTests_X64.SmokeTests_X64_IISExpress_Clr
SmokeTests_X64.SmokeTests_X64_IISExpress_CoreClr_Portable
SmokeTests_X64.SmokeTests_X64_IISExpress_CoreClr_Standalone

http://aspnetci/viewLog.html?buildTypeId=Lite_MusicStoreTest&buildId=339471&branch_Lite_MusicStoreTest=%3Cdefault%3E

cc @Eilon  or @muratg - can we have someone assigned to look at these tests?

**Comment by Eilon** [comment]
@pranavkm do you have time to poke around these tests?

**Comment by natemcmaster** [comment]
@jkotalik thinks this might be a result of required schema changes in the new ANCM.

**Comment by jkotalik** [comment]
It was from the ANCM schema change here: https://github.com/aspnet/AspNetCoreModule/commit/509ddc6ceda29f3318f3df89e5c6872e8e231959. I'll confirm that all CI machines have the schema change.

**Comment by natemcmaster** [comment]
So, to make this work on a non-CI box, what does a dev need to change?

**Comment by jkotalik** [comment]
This schema change will eventually be bundled in the Server Hosting Bundle, so customers will not need to change anything. For us, you pretty much need to update the aspnetcore_schema.xml with this change: https://github.com/aspnet/AspNetCoreModule/commit/509ddc6ceda29f3318f3df89e5c6872e8e231959 in three places: IIS Express 32 bit, 64 bit, and full IIS. This is the script I used to update the schema on the CI machines https://github.com/aspnet/Infrastructure/blob/master/BuildAgent/SetupScripts/DeployANCMSchemas.ps1. Frankly this is a non-ideal solution and it is crummy that it broke everything.

**Comment by jkotalik** [comment]
I have already updated the schemas on all the CI machines. I have also added a fix that avoids AV if the schema change isn't there https://github.com/aspnet/AspNetCoreModule/pull/177.

**Comment by pranavkm** [comment]
Feel free to close this if you think this is enough of a resolution for now.

**Comment by jkotalik** [comment]
I think this is good, I'll reopen if there are more issues.
