### ISSUE TITLE
Error in directory.build.target file(Visual studio 2017 Asp.Net Core 1.1)

### ISSUE THREAD

**Issue by BUBAIMITRA** [aspnet/MusicStore#827]
Hello, 
        I try to run this  project on visual studio 2017 platform but  it is not running.When I build or rebuild that project I found some error directory.build.target file.

![image](https://user-images.githubusercontent.com/32890969/31701993-a5c6d6c4-b3f1-11e7-92e8-7a47b8970f27.png)
thank you

**Comment by pranavkm** [comment]
@BUBAIMITRA you'll need to run `.\build[cmd|sh] restore` from the command line before launching it in VS.

@jkotalik  could you add a build from source section to this repo's README?

**Comment by jkotalik** [comment]
@pranavkm I'm holding off on the new build instructions for each repo as it may change soon. I can make an exception for this repo though.

**Comment by pranavkm** [comment]
Nevermind then. I thought you missed out on this repo. @BUBAIMITRA https://github.com/aspnet/Home/wiki/Building-from-source has more detailed instructions on building repositories from source. Feel free to reopen this issue if following these instructions do not resolve your issue.

**Comment by BUBAIMITRA** [comment]
Hi pranavKM,
                    Actually I am new in asp.net core.So, can you show me the screen shot, how to build that project.So that I can run it on my own Laptop.

Thank you,
Bubai Mitra

**Comment by BUBAIMITRA** [comment]
Hello Sir, 
             Can you please show me from where I can run .\build[cmd|sh] restore from the command line  this command.
This is new thing to me

**Comment by BUBAIMITRA** [comment]
Hello,
You are pointing to this Command line Prompt.
![image](https://user-images.githubusercontent.com/32890969/31732421-19268542-b456-11e7-8f64-df3cc700efbe.png)

**Comment by pranavkm** [comment]
There's a `build.cmd` in the root of the repository. You'll need to run that.

That said, this particular repository is primarily purposed for testing Asp.Net Core's components and isn't necessarily a very good sample to learn from in particular if you're new to the platform. I'd encourage you to peruse our docs - https://docs.microsoft.com/en-us/aspnet/core/ - which are more suited for learning the framework.
