### ISSUE TITLE
Flaky test: PublishAndRun_Test

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/MusicStore#861]
This test [fails](http://aspnetci/viewLog.html?buildId=513796&buildTypeId=Lite_MusicStoreTest) occasionally with the following error:
```
System.Exception : Command exited unexpectedly with exit code: 255
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
   at Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer.StartSelfHostAsync(Uri hintUrl)
   at Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer.DeployAsync()
   at E2ETests.PublishAndRunTests.PublishAndRun_Test(TestVariant variant) in C:\b\w\33bdfc1cae7b2a38\modules\MusicStore\test\MusicStore.E2ETests\PublishAndRunTests.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test PublishAndRun_Test-Server: Kestrel, TFM: netcoreapp2.0, Type: Portable, Arch: x64 at 2018-07-24T20:24:23
| [0.001s] TestLifetime Information: Starting test PublishAndRunTests_Server: Kestrel, TFM: netcoreapp2.0, Type: Portable, Arch: x64 at 2018-07-24T20:24:23
| [0.001s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Deploying [Variation] :: ServerType=Kestrel, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| [0.002s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Removing environment variable ASPNETCORE_ENVIRONMENT
| [0.002s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing command dotnet publish  --output "C:\b\t\buildTmp\e1cb0385-b63f-4b80-8d9e-b6951441b036" --framework netcoreapp2.0 --configuration Release --no-restore -p:VerifyMatchingImplicitPackageVersion=false 
| [0.232s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
| [0.232s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout: Copyright (C) Microsoft Corporation. All rights reserved.
| [1.021s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   MusicStore -> C:\b\w\33bdfc1cae7b2a38\modules\MusicStore\samples\MusicStore\bin\Release\netcoreapp2.0\MusicStore.dll
| [1.023s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   MusicStore -> C:\b\w\33bdfc1cae7b2a38\modules\MusicStore\samples\MusicStore\bin\Release\netcoreapp2.0\MusicStore.Views.dll
| [2.297s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet-publish stdout:   MusicStore -> C:\b\t\buildTmp\e1cb0385-b63f-4b80-8d9e-b6951441b036\
| [2.353s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet publish finished with exit code : 0
| [2.353s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Executing dotnet C:\b\t\buildTmp\e1cb0385-b63f-4b80-8d9e-b6951441b036\MusicStore.dll --urls http://127.0.0.1:0/ --server Microsoft.AspNetCore.Server.Kestrel
| [2.353s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Removing environment variable ASPNETCORE_ENVIRONMENT
| [2.353s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| [2.353s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: SET Data__DefaultConnection__ConnectionString=Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=MusicStore_Test_f289a08d95ac407c94cbfa66158ed0ff;Integrated Security=True;MultipleActiveResultSets=True;Connect Timeout=30
| [2.355s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: Started dotnet. Process Id : 5248
| [5.296s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: Application startup exception: System.AggregateException: One or more errors occurred. (Keyword not supported: 'PoolBlockingPeriod'.) ---> System.ArgumentException: Keyword not supported: 'PoolBlockingPeriod'.
| [5.296s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:    at System.Data.SqlClient.SqlConnectionStringBuilder.Reset(Keywords index)
| [5.296s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:    at System.Data.SqlClient.SqlConnectionStringBuilder.Clear()
| [5.296s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:    at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
| [5.296s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:    at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.CreateMasterConnection()
| [5.297s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:    at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<CreateAsync>d__12.MoveNext()
| [5.297s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: --- End of stack trace from previous location where exception was thrown ---
| [5.297s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
| [5.297s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
| [5.297s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout:    at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.<EnsureCreatedAsync>d__18.MoveNext()
| [5.297s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Information: dotnet stdout: --- End of stack trace from previous location where exception was thrown ---
| [5.297s] Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer Informat
...
```

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=513796&buildTypeId=Lite_MusicStoreTest).

**Comment by ryanbrandenburg** [comment]
This is the same basic problem as aspnet/EntityFrameworkCore#12706.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=513798&buildTypeId=XPlat_Windows_Win10Universe).

**Comment by ryanbrandenburg** [comment]
OpenIdConnectTestSuite [failed again](http://aspnetci/viewLog.html?buildId=513800&buildTypeId=XPlat_Windows_Win7_Universe).

**Comment by ryanbrandenburg** [comment]
NtlmAuthenticationTest [failed again](http://aspnetci/viewLog.html?buildId=513794&buildTypeId=XPlat_Windows_Win8_Universe).

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=516957&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=517017&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by jkotalik** [comment]
I can handle the IIS test failures.

**Comment by natemcmaster** [comment]
This is more than just a flaky tests. It fails consistently.

```
System.AggregateException: One or more errors occurred. (Keyword not supported: 'PoolBlockingPeriod'.) ---> System.ArgumentException: Keyword not supported: 'PoolBlockingPeriod'.
   at System.Data.SqlClient.SqlConnectionStringBuilder.Reset(Keywords index)
   at System.Data.SqlClient.SqlConnectionStringBuilder.Clear()
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.CreateMasterConnection()
```

This looks like more fallout from https://github.com/dotnet/corefx/issues/30720

cc @smitpatel any idea if this has flowed into a corefx build yet?

**Comment by jkotalik** [comment]
I think the rest of tests are fine now based on the latest test run. Only inproc tests are failing.

**Comment by natemcmaster** [comment]
I see. I'm seeing a bunch of failures on VSTS too, btw. https://dotnet.visualstudio.com/public/_build/results?buildId=8453&view=ms.vss-test-web.test-result-details

**Comment by smitpatel** [comment]
My preliminary testing shows that the fix is available in SqlClient package version 4.6.0-preview1-26725-04

Let's see result of https://github.com/aspnet/EntityFrameworkCore/pull/12829

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=517196&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=517878&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=517986&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=518163&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=518306&buildTypeId=Lite_MusicStore).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=518436&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=518392&buildTypeId=XPlat_Windows_Win8_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=518379&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=518375&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=518373&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=518450&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=518510&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=518585&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=518699&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=518651&buildTypeId=XPlat_Windows_Win8_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=518638&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=518634&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=518632&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=518926&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=518816&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=518812&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=519073&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=519050&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=519091&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
PublishAndRun_Test [failed again](http://aspnetci/viewLog.html?buildId=519046&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by jkotalik** [comment]
https://github.com/aspnet/MusicStore/pull/862 should fix this issue. 2.1 shouldn't have been run with IIS in-proc.
