### ISSUE TITLE
Build fails in VS 2017

### ISSUE THREAD

**Issue by thusithagh** [aspnet/MusicStore#866]
Restoring nuget packages fails, hence the build fails in VS2017.

Error:
NuGet package restore canceled.
Error occurred while restoring NuGet packages: The feed 'dotnet-core [https://dotnet.myget.org/F/dotnet-core/api/v3/index.json]' lists package 'runtime.win-x64.Microsoft.NETCore.DotNetHostPolicy.2.2.0-preview1-26618-02' but multiple attempts to download the nupkg have failed. The feed is either invalid or required packages were removed while the current operation was in progress. Verify the package exists on the feed and try again.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @thusithagh. We're closing this issue as ASP.NET Core 2.2 has already been released. If you still experience a similar issue, please report it in aspnet/AspNetCore repository.
